name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Updated to use the latest stable version

      - name: Install and Setup Flutter
        uses: subosito/flutter-action@v3 # Updated to use the latest stable version
        with:
          channel: 'stable'
          flutter-version: '3.2.2' # Specify the Flutter version if needed

      - name: Disable Flutter Analytics
        run: flutter config --no-analytics

      - name: Install Dependencies
        run: flutter pub get

      - name: Build
        run: flutter build web --release --web-renderer canvaskit

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v1 # Updated to use the latest stable version

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1 # Updated to use the latest stable version
        with:
          path: ./build/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 # Updated to use the latest stable version
        
